# Copyright 2023 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

name: 'Check OWNER files'

on:
  schedule:
    - cron: '0 1,13 * * 1-5' # 6am/pm Pacific, weekdays.
  workflow_dispatch: {}

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-matrix.outputs.repos }}
    steps:
    - uses: actions/checkout@v6
    - id: set-matrix
      run: |
        set -x
        echo "repos=$(yq -o=json -I=0 '[ .[] | .name ]' repos.yaml)" >> $GITHUB_OUTPUT

  check:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.matrix.outputs.repos) }}

    steps:
     - name: OWNER_ALIASES up to date
       if: always()
       run: |
         ORG="$(echo '${{ matrix.repo }}' | awk -F '/' '{print $1}')"

         curl --fail -L https://raw.githubusercontent.com/${{ matrix.repo }}/main/OWNERS_ALIASES >repo-owners
         curl --fail -L https://raw.githubusercontent.com/knative/community/main/peribolos/$ORG-OWNERS_ALIASES >community-owners
         diff repo-owners community-owners
