# Copyright 2023 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is automagically generation from ./hack/update-workflows.sh

name: 'knative-extension/eventing-autoscaler-keda'

on:
  schedule:
    - cron: '0 13 * * 1-5' # 6am Pacific, weekdays.

  workflow_dispatch:
    inputs:
      release:
        type: string
        required: false
        description: Release Version

jobs:
  releasability:
    uses: ./.github/workflows/releasability.yaml
    with:
      repo: knative-extension/eventing-autoscaler-keda
      release: ${{ inputs.release }}
      post-to-slack: ${{ github.event_name != 'schedule' }}
    secrets: inherit
